name: nomad_app
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_bloc: ^9.1.1
  bloc: ^9.0.0
  equatable: ^2.0.7
  go_router: ^15.2.0
  get_it: ^8.0.3
  firebase_core: ^3.14.0
  firebase_auth: ^5.6.0
  cloud_firestore: ^5.6.9
  flutter_stripe: ^11.5.0
  flutter_localizations:
    sdk: flutter
  intl: ^0.19.0
  http: ^1.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  
  # Uncomment this section when we have assets
  # assets:
  #   - assets/images/

  # Localization settings
flutter_intl:
  enabled: true
  main_locale: en
  arb_dir: lib/l10n
  output_dir: lib/generated
